### ISSUE TITLE
Moodle para testes com o uso de banco de perguntas - OwpogaLab

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/qualiquiz#13]
Dadas as dificuldades em conseguirmos um servidor de homologação para a realização de testes, coloco a disposição uma Versão Moodle 2.6 para a realização de testes e experimentos na criação de banco de perguntas/respostas
http://ead.owpoga.com/

**Comment by uira** [comment]
@drmarcos ótimo, tinha que instalar um plugin de autenticação com o KeyCloack pra testar... 

Me libera um admin dessa bagaça pra gente brincar semana que vem;)

**Comment by drmarcos** [comment]
Usuário criado
Caso encontre problemas para acessar, tipo seu print de ontem, atualize a página.
Estou com alguns problemas com os servidores da minha hospedagem, esse momento de trabalhos HO, estão dificultando pois a equipe está reduzida tbm na empresa onde faço essa hospedagem.
Os editores wyswyg tem alguns momentos que não aparecem, ai tem que ou atualizar ou sair da página e voltar.
O mesmo tem acontecido com algumas imagens.
