### ISSUE TITLE
Reimplementar tela de boas vindas do qualiquiz

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/qualiquiz#19]
# Objetivo

**Como** pessoa avaliadora dos profissionais da saúde  
**Quero** reimplementar a tela de boas vindas  
**Para** se adequar ao novo design do MVP2

# Contexto

O projeto do QualiQuiz foi reformulado para uma nova usabilidade com uma melhor experiência para  pessoa usuária.
Para esta experiência a tela de Boas Vindas necessita ser reformulada para apresentar melhor o contexto do qualiquiz.

A ideia inicial é fazer a união de duas telas já demonstrada no Figma: Sobre e a de Introdução do Quiz (Manejo Clínico).
Sem a opção de escolher como visualizar a resposta, pois, inicialmente, a resposta será exibida ao fim do quiz.

# Escopo

- [ ] Implementar a tela de acordo com o projeto desenhado

# Critérios de Aceitação

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

[Protótipo da tela](https://www.figma.com/file/yMLBZsAIPVr0wYswUNXAGz/MVP-01?node-id=1%3A101)

**Comment by wforte88** [comment]
![image](https://user-images.githubusercontent.com/21333612/125789184-db3d7b8a-a0b2-4921-87d5-b0f85d3cd597.png)
