### ISSUE TITLE
Substituir imagem do Loading quando iniciar o quiz

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/qualiquiz#20]
# Objetivo

**Como** pessoa avaliadora dos profissionais da saúde  
**Quero** modificar o loading do qualiquiz 
**Para** se adequar ao novo design do MVP2

# Contexto

A tela de carregamento do qualiquiz é uma imagem que não referencia o projeto.
Será substituída a imagem genérica por uma logo do qualiquiz

# Escopo

- [x] escopo1

# Fora de Escopo

- fora_de_escopo

# Critérios de Aceitação

- [x] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações
[Protótipo da tela](https://www.figma.com/file/yMLBZsAIPVr0wYswUNXAGz/MVP-01?node-id=1%3A101)
[ProgressBar.zip](https://github.com/EscolaDeSaudePublica/qualiquiz/files/6841310/ProgressBar.zip)

**Comment by wforte88** [comment]
![ProgressBar](https://user-images.githubusercontent.com/21333612/125791694-cf5071c8-e30f-45e8-a7bb-c74ad0b32f76.gif)

**Comment by wforte88** [comment]
Adicionado arquivo **ProgressBar.zip** com loader no formatos SVG e GIF
