### ISSUE TITLE
Atualizar tela de confirmação do envio das questões

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/qualiquiz#22]
# Objetivo

**Como** pessoa avaliadora dos profissionais da saúde
**Quero** atualizar o design da tela de confirmação de envio
**Para** se adequar ao novo design do MVP2

# Contexto

O projeto do QualiQuiz foi reformulado para uma nova usabilidade com uma melhor experiência para pessoa usuária.
Para esta experiência a tela de Confirmação necessita ser reformulada para se adequar ao novo design.

# Escopo

- [ ] escopo1

# Fora de Escopo

- fora_de_escopo

# Critérios de Aceitação

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

## Imagem de referência

![image](https://user-images.githubusercontent.com/6399202/126173068-0fb9bfb2-044c-42aa-872f-1e6d0404b71f.png)

## Prototipo figma

[Protótipo da tela](https://www.figma.com/file/yMLBZsAIPVr0wYswUNXAGz/MVP-01?node-id=1%3A124)

**Comment by wforte88** [comment]
![image](https://user-images.githubusercontent.com/21333612/125788953-ca526e3b-d8a4-42ae-b6eb-79e6bd04ee7a.png)
