### ISSUE TITLE
Criar tela Todas Avaliações

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/qualiquiz#42]
# Objetivo

**Como** persona  
**Quero** fazer_algo  
**Para** uma_finalidade

# Contexto

-

# Escopo

- [ ] escopo1

# Fora de Escopo

- 

# Critérios de Aceitação

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

ex: Prototipo

**Comment by ericsonmoreira** [comment]
Acho que esse card está duplicado.
