### ISSUE TITLE
Atualização do `Qualiquiz`

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/qualiquiz#75]
# Objetivo

**Como** personas desenvolvedoras do `Qualiquiz` 
**Queremos** entender do procedimento de deploy 
**Para** podermos ter a autonomia de atualizar a aplicação quando necessário

# Contexto

Atualmente, o procedimento de atualização do `Qualiquiz` é feito pelo @victorMagalhaesPacheco mas necessitamos de autonomia desse procedimento.

Então, foi agendada uma reunião para o dia 30/09 às 14:00 para que ele possa passar para a equipe de desenvolvimento os procedimentos necessários para essa atualização dos ambientes de produção e homologação.

## Link da reunião: 

Tutorial para atualização do Qualiquiz
Quinta-feira, 30 de setembro · 14:00 até 15:00
Informações de participação do Google Meet
Link da videochamada: https://meet.google.com/ajj-xgpv-omy

**Comment by ericsonmoreira** [comment]
Infelizmente, tivemos que reagendar a reunião.

**Comment by JefersonNSoares** [comment]
Realizada reunião para alinhar as informações de atualização do Qualiquiz.
Ericson irá providenciar os acessos para realizar os deploy do Qualiquiz.
