### ISSUE TITLE
Acompanhamento da Aplicação - Qualiquiz

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/qualiquiz#96]
Gerar página web (utilizando o METABASE) com o acompanhamento das Avaliações Qualiquiz realizadas.

Observar modelo orientativo da página desejada nas imagens a seguir:
![Slide4.JPG](https://images.zenhubusercontent.com/613b5ddea639049db13b61d9/90cf4707-61d1-4793-ad32-ec0dc433e452)
![Slide5.JPG](https://images.zenhubusercontent.com/613b5ddea639049db13b61d9/f80deb87-94ee-4f8b-8deb-2e982e9b3924)
-------------------------------------------------------------------------------------------
A página deverá ser apresentada por Quiz - Categoria Profissional  - Especialidade e gerada em tempo real.

Indicadores:
http://metabase.esp.ce.gov.br/public/dashboard/5625fd38-bd17-4638-8545-993adfb01824

**Comment by camilaccolares** [comment]
![MER qualiquiz](https://user-images.githubusercontent.com/58710064/145270495-510c9e09-d9f6-4909-8e7e-784042d379af.png)

**Comment by aislansf** [comment]
Já realizei algumas atividades

- Baixei os arquivos csv da tabela;
- Criei a base de dados no Datawarehouse
- Desenvolvi os sql já com os insert dos arquivos csv

Agora vou iniciar a construção da primeira dashboard com os dados em mãos.

**Comment by aislansf** [comment]
@Laysacunha qual a unidade da coluna tempo da tabela qquiz_respostas?

Você pode enviar a tabela que tem o CBO, especilidade e município dos usuários que realizaram o quiz?

**Comment by aislansf** [comment]
Pessoas segue o link da dashboard desenvolvidas com os dados que foram passados para o time Datalab.

http://metabase.esp.ce.gov.br/public/dashboard/7f282af7-ec61-41d8-a16f-54efd2e731a4

Aguardo avaliação dos envolvidos para seguir nos próximos passos, se houver.

**Comment by camilaccolares** [comment]
[QUALIQUIZ-AVALIACAO-PRELIMINAR.pptx](https://github.com/EscolaDeSaudePublica/qualiquiz/files/7846939/QUALIQUIZ-AVALIACAO-PRELIMINAR.pptx)

**Comment by janeteamaral** [comment]
Segue link atual do relatório no Metabase http://metabase.esp.ce.gov.br/public/dashboard/5625fd38-bd17-4638-8545-993adfb01824
Precisamos do posicionamento do Designlab para correções necessárias.

**Comment by RaniGub** [comment]
Marcado pareamento com a @janeteamaral para dia 17/01/2022 às 10h.

**Comment by RaniGub** [comment]
Análise e sugestões DesignLab:
Gráfico 1 - Permanece como está.
Indicativo de tempo 1 - Minutos deve estar na mesma linha do numeral 21, ou a abreviação 'min'.
Gráfico 2 - Colocar no formato do Mapa do Ceará, foi adicionada uma imagem de referência do IntegraSUS.
Gráfico 3 - Permanece como está.
Gráfico 4 - Permanece como está.
Gráfico 5 - 
I) A contagem do campo 'alternativa', quando se passa o mouse sobre o gráfico, é crescente no decorrer das questões. Se não houve justificativa para leitura como indicador de total de alternativas no Quiz, seria mais interessante que a cada grupo de 4 alternativas (a,b,c e d), a contagem reinicie do 1;
II) O label 'Contagem' poderia passar a ser 'Acertos' e vir em terceiro da lista;
III) A linha dos gráficos está muito fina, o que reduz a área de interação. É possível deixar um pouco mais espessa?

Referência da sugestão do Gráfico 2
![Captura de Tela 2022-01-17 às 09.29.12.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/e5508a35-7d5f-4151-acaf-78562666f2a1)

Referência da sugestão do Gráfico 5 (Itens I e II)
![Captura de Tela 2022-01-18 às 13.51.32.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/b7bc1e58-b41b-492b-a904-737b1e52eff2)

**Comment by aislansf** [comment]
Perfeito! Já peguei as orientações e breve retornarei com as correções.

**Comment by aislansf** [comment]
@RaniGub e @janeteamaral vou fazer algumas considerações sobre os pontos de melhoria.
Estamos utilizando a ferramenta metabase para construir nossos dashboards, ela possui algumas limitações e é o que está disponibilizado para o time do datalab desenvolver suas atividades. Agora vamos aos pontos destacados pelo @RaniGub:

- No indicativo de tempo infelizmente não conseguimos colocar ao lado o "min", mas por padrão do metabase ele sempre adiciona na parte inferior do número.
- Em relação ao mapa foi adicionado como sugerido, porém, existem algumas coisas que se dá pelo padrão da plataforma.
- O gráfico da contagem dos itens não conseguimos aumentar a espessura, sobre o número da alternativa é uma informação que vem diretamente do banco, isso podemos conversar com a @janeteamaral para ver a melhor forma de alterar isso no banco, se for o caso. Sobre o label "Contagem" não pode ser considerado como "Acerto" por que esse label representa quantos alunos responderam cada item, se eu estiver entendido errado a @janeteamaral pode corrigir.

Estou sempre à disposição de todos e qualquer coisa é só entrar em contato.

Está diponível para análise e validação dos ajustes.

**Comment by RaniGub** [comment]
Ahhh entendi @aislansf, você tem razão. Obrigado pelo retorno.

**Comment by RaniGub** [comment]
@aislansf o título do gráfico 2 não está aparecendo. Sugiro que seja: Tempo médio de resposta do Quiz.

**Comment by aislansf** [comment]
@RaniGub feito a substituição do título para o gráfico 2

**Comment by marameida** [comment]
Conversado com Laysa. No momento ainda aguardar deliberação sobre responsável pelo Qualiquiz para aprovação do que já foi produzido.

**Comment by marameida** [comment]
Solicitada reunião com Batista e Natana para validação do que já foi produzido. No aguardo por retorno.

**Comment by uira** [comment]
@marameida Recebemos uma demanda deles, de informar os dados de acesso ao QualiQuiz.

Importante incluir isso na pauta, pra saber quais informações eles precisam, e aí incluírmos ou elaborarmos novo painel

**Comment by marameida** [comment]
Primeira reunião de pré-validação realizada com Natana e Jackanderson. @uira colocada essa questão sobre dados de acesso ao Qualiquiz. Validação amanhã às 16h com a preença do Dr Batista.

**Comment by marameida** [comment]
Sugestões pendentes:
- Volume de acesso;
- Adicionar filtro por data;
- Faz sentido manter quizes inativos?;

**Comment by marameida** [comment]
Encaminhamentos da reunião de hoje com Dr Batista:
Demadas a serem complementadas para entrega:
1- Listar as perguntas passando com o mouse. 
2- Colocar período (filtro por período) e volume de acesso. 
3- Gerar planilha/relatório dos dados. 
4- Puxar dados do perfil cadastrado do participante* (só se for algo rápido - se demorar, fica para depois)
